#!/bin/sh

PATH=/sbin:/bin
umask 022
export PATH

# mount nodes
mount -t proc /proc /proc
mount -t ramfs none /dev
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug

# /dev nodes
mknod /dev/null c 1 3
mknod /dev/zero c 1 5
#mknod /dev/tty  c 5 0
mknod /dev/console  c 5 1
#mknod /dev/tty0 c 4 0
#mknod /dev/tty1 c 4 1
#mknod /dev/tty2 c 4 2
#mknod /dev/tty3 c 4 3
#mknod /dev/tty4 c 4 4
mknod /dev/ttyS0 c 4 64
mknod /dev/ttyS1 c 4 65
mknod /dev/ttyS2 c 4 66
mknod /dev/ttyS3 c 4 67

# soft links
ln -sf /dev/null /dev/tty2
ln -sf /dev/null /dev/tty3
ln -sf /dev/null /dev/tty4
