obj-y += arch_init_irq.o         \
         get_system_type.o       \
         plat_irq_dispatch.o     \
         plat_mem_setup.o        \
         plat_time_init.o        \
         prom_free_prom_memory.o \
         prom_init.o             \
         prom_putchar.o

obj-$(CONFIG_OF) +=  device_tree_init.o
obj-$(CONFIG_OF) +=  plat_of_setup.o


